CIUDADES = [
    "Barcelona",
    "L'Hospitalet de Llobregat",
    "Badalona",
    "Santa Coloma de Gramenet",
    "Cornellà de Llobregat",
    "Sant Boi de Llobregat",
    "Sant Adrià de Besòs",
    "Esplugues de Llobregat",
    "Sant Just Desvern",
    "Sant Feliu de Llobregat",
    "Molins de Rei",
    "El Prat de Llobregat",
    "Viladecans",
    "Gavà",
    "Castelldefels",
    "Cerdanyola del Vallès",
    "Ripollet",
    "Montcada i Reixac",
    "Sabadell",
    "Terrassa",
    "Mataró",
    "Granollers",
]
