-- Actualiza el campo `instrucciones` de las 28 recetas con pasos numerados,
-- detallados y en líneas independientes (tiempos, temperaturas y técnicas).
--
-- IMPORTANTE sobre el formato: se usan cadenas E'...' (escape string de PostgreSQL),
-- no cadenas simples '...'. Con `standard_conforming_strings = on` (el valor por
-- defecto desde hace años), una cadena simple '...' NO interpreta '\n' como salto de
-- línea: guarda literalmente los dos caracteres "\" y "n". Solo las cadenas E'...'
-- procesan '\n' como salto de línea real, que es lo que necesita el frontend
-- (Angular renderiza `instrucciones` con `white-space: pre-line`, así que hacen
-- falta saltos de línea reales, no el texto literal "\n").
--
-- Los ingredientes mencionados en cada paso coinciden exactamente con los vínculos
-- ya sembrados en receta_ingredientes (ver backend/seeds/recetas_ingredientes.sql).

BEGIN;

UPDATE recetas SET instrucciones = E'1. Lava bien la lechuga, el perejil, la albahaca y el pepino bajo agua fría abundante.\n2. Corta la lechuga en juliana fina y colócala como base en un bowl amplio.\n3. Pela el pepino y córtalo en medias lunas de unos 5 mm de grosor.\n4. Parte los tomates cherry por la mitad con un cuchillo de sierra para no aplastarlos.\n5. Pica finamente el perejil y la albahaca en el último momento, para que no se oxiden.\n6. Distribuye el pepino y los tomates cherry sobre la lechuga y termina con las hierbas picadas por encima.\n7. Sirve inmediatamente para que las hojas mantengan su textura crujiente.' WHERE id_receta = 1;

UPDATE recetas SET instrucciones = E'1. Lava los tomates y sécalos bien con papel de cocina.\n2. Corta los tomates en rodajas de aproximadamente 1 cm de grosor.\n3. Corta la mozzarella en rodajas del mismo grosor que el tomate.\n4. En un plato llano, alterna una rodaja de tomate con una de mozzarella, formando un abanico.\n5. Reparte las hojas de albahaca fresca entera entre las rodajas.\n6. Riega con un buen chorro de aceite de oliva virgen extra.\n7. Sazona con sal y pimienta negra recién molida justo antes de servir.\n8. Deja reposar 5 minutos a temperatura ambiente para que los sabores se asienten.' WHERE id_receta = 2;

UPDATE recetas SET instrucciones = E'1. Lava bien el perejil y el cilantro, y sécalos con un paño limpio.\n2. Retira los tallos más gruesos y quédate solo con las hojas y tallos tiernos.\n3. Pela los dientes de ajo y córtalos por la mitad, retirando el germen central para que no repitan.\n4. Introduce las hierbas, el ajo y el aceite de oliva en el vaso de la batidora.\n5. Añade el zumo de limón recién exprimido y una pizca de sal.\n6. Tritura a velocidad media hasta obtener una textura homogénea, parando a rascar las paredes si hace falta.\n7. Prueba y rectifica de sal o limón según tu gusto.\n8. Guarda en un tarro hermético en la nevera; se conserva bien hasta una semana.' WHERE id_receta = 3;

UPDATE recetas SET instrucciones = E'1. Lava bien los tomates, el pepino y el pimiento.\n2. Trocea los tomates, el pepino, el pimiento y la cebolla en trozos grandes para facilitar el triturado.\n3. Coloca todas las verduras en el vaso de la batidora junto con el aceite de oliva y el vinagre.\n4. Añade una pizca de sal y tritura a máxima potencia entre 2 y 3 minutos hasta lograr una textura fina.\n5. Pasa la mezcla por un colador fino o un chino si prefieres una textura más sedosa.\n6. Rectifica de sal y vinagre al gusto.\n7. Refrigera al menos 2 horas antes de servir; cuanto más frío, mejor sabe en verano.\n8. Sirve en boles o vasos individuales con un chorrito extra de aceite de oliva por encima.' WHERE id_receta = 4;

UPDATE recetas SET instrucciones = E'1. Lava bien el pepino y las hojas de menta.\n2. Corta el pepino en rodajas finas, sin necesidad de pelarlo si es ecológico.\n3. Exprime el limón y cuela el zumo para evitar pepitas.\n4. En una jarra grande, coloca las rodajas de pepino y las hojas de menta ligeramente aplastadas con la mano para liberar su aroma.\n5. Añade el zumo de limón y completa con agua fría hasta llenar la jarra.\n6. Deja reposar en la nevera un mínimo de 30 minutos para que los sabores se infusionen.\n7. Sirve bien fría, con hielo y una rodaja extra de pepino como decoración.' WHERE id_receta = 5;

UPDATE recetas SET instrucciones = E'1. Lava y seca muy bien las hojas de albahaca; la humedad estropea la conservación del pesto.\n2. Tuesta ligeramente los piñones en una sartén sin aceite durante 1-2 minutos, vigilando que no se quemen.\n3. Pela los ajos y retira el germen central para suavizar su sabor.\n4. En un mortero o procesadora, machaca los piñones junto con el ajo hasta obtener una pasta.\n5. Añade la albahaca poco a poco y sigue majando o triturando.\n6. Incorpora el queso parmesano rallado y mezcla bien.\n7. Añade el aceite de oliva en hilo fino, removiendo hasta emulsionar y conseguir una crema homogénea.\n8. Guarda en un tarro cubierto con una fina capa de aceite por encima para evitar que oxide.' WHERE id_receta = 6;

UPDATE recetas SET instrucciones = E'1. Prepara la marinada mezclando aceite de oliva, romero picado, tomillo, ajo machacado y sal en un bol.\n2. Introduce el pollo en la marinada, cubriéndolo bien, y déjalo reposar en la nevera al menos 30 minutos (idealmente 2 horas).\n3. Mientras tanto, lava y corta el pimiento y la zanahoria en trozos medianos y homogéneos para que se cocinen por igual.\n4. Precalienta el horno a 200°C con calor arriba y abajo.\n5. Calienta una sartén a fuego alto y dora el pollo marinado durante 3 minutos por cada lado, hasta sellar bien la piel.\n6. Coloca el pollo dorado en una bandeja de horno junto con el pimiento y la zanahoria.\n7. Hornea durante 25 minutos, hasta que el pollo alcance los 75°C en su parte más gruesa y las verduras estén tiernas.\n8. Deja reposar 5 minutos fuera del horno antes de trinchar, para que los jugos se redistribuyan.\n9. Espolvorea perejil fresco picado justo antes de servir.' WHERE id_receta = 7;

UPDATE recetas SET instrucciones = E'1. Corta la ternera en tiras finas, siempre en contra de la fibra de la carne para que quede más tierna.\n2. Lava bien las espinacas frescas y escúrrelas.\n3. Pela y lamina el ajo.\n4. Calienta el aceite de oliva en una sartén amplia a fuego medio-alto y dora el ajo laminado hasta que empiece a dorarse, sin que se queme.\n5. Sube el fuego a máximo y sella la ternera durante 2 minutos, removiendo para que se dore de forma uniforme.\n6. Añade las espinacas y saltea 2 minutos más, hasta que se reduzcan pero mantengan su color verde intenso.\n7. Sazona con sal y pimienta negra recién molida.\n8. Aparta del fuego y añade un chorrito de zumo de limón justo antes de servir para realzar los sabores.' WHERE id_receta = 8;

UPDATE recetas SET instrucciones = E'1. Precalienta el horno a 180°C.\n2. Corta la parte superior de los pimientos a modo de "tapa" y vacíalos de semillas con cuidado de no romper las paredes.\n3. Pica finamente la cebolla y los ajos.\n4. En una sartén con un poco de aceite, sofríe la cebolla y el ajo a fuego medio durante 5 minutos, hasta que la cebolla esté transparente.\n5. Añade la carne picada y cocina removiendo hasta que pierda el color rosado, deshaciendo los grumos con una cuchara de madera.\n6. Incorpora el tomate triturado y el orégano, y cocina a fuego suave 10 minutos, hasta que el relleno espese.\n7. Rectifica de sal y añade el cilantro picado fuera del fuego, para que conserve su aroma fresco.\n8. Rellena los pimientos con la mezcla y colócalos en una bandeja de horno.\n9. Hornea durante 30 minutos, hasta que los pimientos estén tiernos y ligeramente dorados por encima.' WHERE id_receta = 9;

UPDATE recetas SET instrucciones = E'1. Lava el calabacín y trocéalo sin necesidad de pelarlo, para aprovechar su color y fibra.\n2. Pica la cebolla y el ajo finamente.\n3. Calienta el aceite de oliva en una olla y sofríe la cebolla y el ajo a fuego medio durante 5 minutos, hasta que estén translúcidos.\n4. Añade el calabacín troceado y rehoga 2 minutos más.\n5. Vierte el caldo vegetal hasta cubrir las verduras y lleva a ebullición.\n6. Baja el fuego y cocina a fuego medio-bajo durante 15 minutos, hasta que el calabacín esté completamente tierno.\n7. Tritura con una batidora de mano hasta obtener una crema fina y homogénea; si queda muy espesa, añade un poco más de caldo.\n8. Sirve caliente (o fría, en verano) decorada con unas hojas de menta fresca picadas.' WHERE id_receta = 10;

UPDATE recetas SET instrucciones = E'1. Lava y seca bien la rúcula y los rábanos.\n2. Corta los rábanos en láminas muy finas, con ayuda de una mandolina si tienes.\n3. Parte los tomates cherry por la mitad.\n4. En un bol grande, mezcla la rúcula, los rábanos laminados y los tomates cherry.\n5. Pica finamente el cebollino y espárcelo por encima.\n6. Prepara una vinagreta rápida mezclando el aceite de oliva con el zumo de limón.\n7. Aliña la ensalada justo antes de servir para que la rúcula no pierda su textura crujiente.' WHERE id_receta = 11;

UPDATE recetas SET instrucciones = E'1. Lava las judías verdes y despunta ambos extremos.\n2. Lleva a ebullición una olla con agua y sal.\n3. Escalda las judías durante 5 minutos, hasta que estén tiernas pero conserven algo de firmeza.\n4. Retíralas y sumérgelas inmediatamente en agua con hielo para cortar la cocción y fijar su color verde intenso.\n5. Escurre bien y reserva.\n6. Lamina el ajo y dóralo en una sartén con aceite de oliva a fuego medio, vigilando que no se queme y amargue.\n7. Añade las judías escurridas y saltea a fuego fuerte durante 3 minutos, removiendo con frecuencia.\n8. Espolvorea perejil fresco picado y sirve inmediatamente.' WHERE id_receta = 12;

UPDATE recetas SET instrucciones = E'1. Lava el kale y retira los tallos más duros del centro de cada hoja.\n2. Trocea las hojas en tiras medianas.\n3. Pela y lamina el ajo.\n4. Calienta el aceite de oliva en una sartén amplia y dora el ajo a fuego medio durante 1 minuto.\n5. Añade el kale y rehoga a fuego medio-alto durante 4 minutos, removiendo para que se cocine de forma uniforme.\n6. Incorpora los guisantes y cocina 3 minutos más, hasta que estén tiernos.\n7. Retira del fuego y exprime el limón por encima justo antes de servir para conservar su frescor.' WHERE id_receta = 13;

UPDATE recetas SET instrucciones = E'1. Lava bien las acelgas y separa las hojas de los tallos, ya que estos necesitan más tiempo de cocción.\n2. Corta los tallos en trozos pequeños y pela y corta la zanahoria en rodajas finas.\n3. Trocea las hojas de acelga en tiras.\n4. Calienta el aceite de oliva en una sartén y sofríe el ajo picado junto con el orégano durante 1 minuto, hasta que desprenda aroma.\n5. Añade los tallos de acelga y la zanahoria, y cocina a fuego medio durante 5 minutos, removiendo de vez en cuando.\n6. Incorpora las hojas de acelga y rehoga 3 minutos más, hasta que se ablanden pero mantengan algo de color.\n7. Rectifica de sazón y sirve caliente.' WHERE id_receta = 14;

UPDATE recetas SET instrucciones = E'1. Corta el pan en rebanadas de aproximadamente 1,5 cm de grosor.\n2. Tuesta las rebanadas en una sartén, plancha o tostadora hasta que estén doradas y crujientes por ambos lados.\n3. Frota un diente de ajo pelado sobre el pan aún caliente; el calor ayuda a que suelte su aroma.\n4. Pica el tomate en dados pequeños y mézclalo con la albahaca picada, un chorro de aceite de oliva y una pizca de sal.\n5. Deja reposar la mezcla de tomate 5 minutos para que se integren los sabores.\n6. Reparte la mezcla sobre las rebanadas de pan justo antes de servir, para que no se ablande el pan.' WHERE id_receta = 15;

UPDATE recetas SET instrucciones = E'1. Precalienta el horno a 200°C.\n2. Corta las berenjenas por la mitad a lo largo.\n3. Haz cortes en forma de rejilla en la pulpa, sin llegar a atravesar la piel, para que se cocinen mejor y absorban el aliño.\n4. Riega generosamente con aceite de oliva y espolvorea el tomillo y el orégano.\n5. Coloca las berenjenas en una bandeja de horno con la pulpa hacia arriba.\n6. Hornea durante 35 minutos, hasta que la pulpa esté muy tierna y ligeramente dorada.\n7. Sirve recién salidas del horno, cuando están en su punto óptimo de sabor y textura.' WHERE id_receta = 16;

UPDATE recetas SET instrucciones = E'1. Lava las fresas con cuidado y retírales el rabito.\n2. Córtalas por la mitad o en cuartos si son grandes.\n3. Pica finamente las hojas de menta.\n4. Mezcla las fresas con la menta picada en un bol.\n5. Si lo deseas, añade un chorrito de zumo de limón para realzar el dulzor natural de la fruta.\n6. Deja macerar en la nevera 10 minutos antes de servir para que los sabores se integren.' WHERE id_receta = 17;

UPDATE recetas SET instrucciones = E'1. Lava el pepino y córtalo en rodajas finas (puedes pelarlo parcialmente si prefieres menos amargor).\n2. En un bol, mezcla el yogur con el cebollino picado.\n3. Sazona la mezcla de yogur con sal y pimienta negra recién molida.\n4. Incorpora las rodajas de pepino a la mezcla y remueve con cuidado para que se impregnen bien.\n5. Deja reposar en la nevera 10 minutos antes de servir, para que el pepino se enfríe y absorba el sabor del aliño.' WHERE id_receta = 18;

UPDATE recetas SET instrucciones = E'1. Precalienta el horno a 200°C.\n2. Pela las zanahorias y córtalas en bastones o mitades a lo largo, según su grosor.\n3. Colócalas en una bandeja de horno y riégalas con aceite de oliva.\n4. Añade el romero y el tomillo repartidos por encima.\n5. Hornea durante 30 minutos, dando la vuelta a mitad de cocción para que se doren de manera uniforme.\n6. Sirve calientes, recién salidas del horno, cuando están más caramelizadas.' WHERE id_receta = 19;

UPDATE recetas SET instrucciones = E'1. Pela los ajos y pica el tomate en trozos.\n2. Calienta un chorro de aceite en una sartén y sofríe el ajo a fuego medio hasta que empiece a dorarse.\n3. Añade el tomate troceado y cocina 5 minutos, hasta que empiece a deshacerse.\n4. Incorpora las guindillas troceadas (retira las semillas si prefieres una salsa menos picante).\n5. Cocina a fuego medio-bajo durante 15 minutos, removiendo de vez en cuando, hasta que la salsa reduzca y espese.\n6. Tritura con la batidora hasta obtener una salsa fina; si prefieres textura más rústica, tritura solo parcialmente.\n7. Deja enfriar antes de embotellar; se conserva varios días en la nevera en un recipiente hermético.' WHERE id_receta = 20;

UPDATE recetas SET instrucciones = E'1. Lava la rúcula y las fresas por separado.\n2. Corta las fresas en láminas finas.\n3. Coloca la rúcula como base en una fuente o plato.\n4. Reparte las láminas de fresa sobre la rúcula.\n5. Espolvorea el cebollino picado por encima.\n6. Aliña con aceite de oliva y un chorrito de zumo de limón justo antes de servir.' WHERE id_receta = 21;

UPDATE recetas SET instrucciones = E'1. Precalienta el horno a 190°C.\n2. Corta los tomates por la mitad y colócalos con el corte hacia arriba en una bandeja de horno.\n3. Pica finamente el ajo y repártelo sobre cada mitad de tomate.\n4. Espolvorea el orégano y el tomillo por encima.\n5. Hornea durante 25 minutos, hasta que los tomates estén tiernos y ligeramente dorados en el borde.\n6. Retira del horno y decora con albahaca fresca picada antes de servir.' WHERE id_receta = 22;

UPDATE recetas SET instrucciones = E'1. Pela y trocea la zanahoria, la cebolla y el ajo.\n2. Sofríe la cebolla y el ajo en una olla con un poco de aceite a fuego medio durante 5 minutos.\n3. Añade la zanahoria troceada y rehoga 2 minutos más.\n4. Vierte el caldo vegetal hasta cubrir las verduras y añade el tomillo.\n5. Cocina a fuego medio durante 25 minutos, hasta que la zanahoria esté muy tierna.\n6. Retira las ramas de tomillo y tritura con la batidora hasta lograr una crema fina.\n7. Rectifica el punto de sal y sirve caliente.' WHERE id_receta = 23;

UPDATE recetas SET instrucciones = E'1. Precalienta el horno a 200°C.\n2. Corta las berenjenas por la mitad y ásalas durante 25 minutos, hasta que estén tiernas.\n3. Mientras tanto, pica el ajo y el tomate.\n4. En una sartén con un poco de aceite, cocina el ajo y el tomate a fuego medio durante 10 minutos, hasta obtener una salsa espesa.\n5. Retira la berenjena del horno y cúbrela con la salsa de tomate.\n6. Termina con albahaca fresca picada por encima antes de servir.' WHERE id_receta = 24;

UPDATE recetas SET instrucciones = E'1. Lava los fresones y retírales el rabito.\n2. Trocéalos y colócalos en una olla junto con el azúcar y el zumo de limón.\n3. Deja macerar 30 minutos para que los fresones suelten su jugo.\n4. Cocina a fuego medio, removiendo con frecuencia para que no se pegue al fondo.\n5. Cuando rompa a hervir, baja el fuego y cocina 20-25 minutos, hasta que espese y alcance el punto de mermelada.\n6. Comprueba el punto poniendo una gota en un plato frío: si no resbala al inclinarlo, está lista.\n7. Envasa en tarros de cristal esterilizados aún caliente y cierra bien.' WHERE id_receta = 25;

UPDATE recetas SET instrucciones = E'1. Lava las hierbas (romero, tomillo y orégano) y sécalas muy bien; la humedad puede estropear el aceite.\n2. Introduce las hierbas en una botella de cristal limpia y seca.\n3. Cubre completamente con aceite de oliva, asegurándote de que las hierbas queden sumergidas.\n4. Cierra la botella y guárdala en un lugar fresco y oscuro.\n5. Deja infusionar durante al menos una semana antes de usarlo, agitando la botella de vez en cuando.\n6. Cuela el aceite si prefieres una textura más limpia, o consérvalo con las hierbas dentro para más intensidad.' WHERE id_receta = 26;

UPDATE recetas SET instrucciones = E'1. Lava los pepinos y córtalos en rodajas o bastones, según prefieras.\n2. Pela y lamina los dientes de ajo.\n3. Coloca los pepinos y el ajo en un bote de cristal limpio.\n4. Añade el orégano y cubre todo con vinagre hasta que quede completamente sumergido.\n5. Cierra el bote y refrigera durante al menos 24 horas antes de consumir.\n6. Se conservan en la nevera hasta dos semanas; cuanto más tiempo reposan, más intenso es el sabor.' WHERE id_receta = 27;

UPDATE recetas SET instrucciones = E'1. Lava las guindillas y sécalas bien.\n2. Si prefieres un encurtido menos picante, haz un pequeño corte en cada guindilla para que suelten parte de su intensidad.\n3. Colócalas en un tarro de cristal limpio y esterilizado.\n4. Cubre completamente con vinagre.\n5. Cierra bien el tarro y deja reposar en un lugar fresco durante varios días antes de consumir.\n6. Usa guantes al manipular las guindillas para evitar irritación en la piel.' WHERE id_receta = 28;

COMMIT;
